export const countries = [
  // Países de habla inglesa o española (activos)
  {
    nombre: 'Anguila',
    name: 'Anguilla',
    nom: 'Anguilla',
    iso2: 'AI',
    iso3: 'AIA',
    phone_code: '+1 264',
  },
  {
    nombre: 'Antigua y Barbuda',
    name: 'Antigua and Barbuda',
    nom: 'Antigua et Barbuda',
    iso2: 'AG',
    iso3: 'ATG',
    phone_code: '+1 268',
  },
  {
    nombre: 'Argentina',
    name: 'Argentina',
    nom: 'Argentine',
    iso2: 'AR',
    iso3: 'ARG',
    phone_code: '+54',
  },
  {
    nombre: 'Australia',
    name: 'Australia',
    nom: 'Australie',
    iso2: 'AU',
    iso3: 'AUS',
    phone_code: '+61',
  },
  {
    nombre: 'Bahamas',
    name: 'Bahamas',
    nom: 'Bahamas',
    iso2: 'BS',
    iso3: 'BHS',
    phone_code: '+1 242',
  },
  {
    nombre: 'Barbados',
    name: 'Barbados',
    nom: 'Barbade',
    iso2: 'BB',
    iso3: 'BRB',
    phone_code: '+1 246',
  },
  {
    nombre: 'Belice',
    name: 'Belize',
    nom: 'Belize',
    iso2: 'BZ',
    iso3: 'BLZ',
    phone_code: '+501',
  },
  {
    nombre: 'Bolivia',
    name: 'Bolivia',
    nom: 'Bolivie',
    iso2: 'BO',
    iso3: 'BOL',
    phone_code: '+591',
  },
  {
    nombre: 'Canadá',
    name: 'Canada',
    nom: 'Canada',
    iso2: 'CA',
    iso3: 'CAN',
    phone_code: '+1',
  },
  {
    nombre: 'Chile',
    name: 'Chile',
    nom: 'Chili',
    iso2: 'CL',
    iso3: 'CHL',
    phone_code: '+56',
  },
  {
    nombre: 'Colombia',
    name: 'Colombia',
    nom: 'Colombie',
    iso2: 'CO',
    iso3: 'COL',
    phone_code: '+57',
  },
  {
    nombre: 'Costa Rica',
    name: 'Costa Rica',
    nom: 'Costa Rica',
    iso2: 'CR',
    iso3: 'CRI',
    phone_code: '+506',
  },
  {
    nombre: 'Cuba',
    name: 'Cuba',
    nom: 'Cuba',
    iso2: 'CU',
    iso3: 'CUB',
    phone_code: '+53',
  },
  {
    nombre: 'Dominica',
    name: 'Dominica',
    nom: 'Dominique',
    iso2: 'DM',
    iso3: 'DMA',
    phone_code: '+1 767',
  },
  {
    nombre: 'Ecuador',
    name: 'Ecuador',
    nom: 'Equateur',
    iso2: 'EC',
    iso3: 'ECU',
    phone_code: '+593',
  },
  {
    nombre: 'El Salvador',
    name: 'El Salvador',
    nom: 'El Salvador',
    iso2: 'SV',
    iso3: 'SLV',
    phone_code: '+503',
  },
  {
    nombre: 'España',
    name: 'Spain',
    nom: 'Espagne',
    iso2: 'ES',
    iso3: 'ESP',
    phone_code: '+34',
  },
  {
    nombre: 'Estados Unidos de América',
    name: 'United States of America',
    nom: "États-Unis d'Amérique",
    iso2: 'US',
    iso3: 'USA',
    phone_code: '+1',
  },
  {
    nombre: 'Filipinas',
    name: 'Philippines',
    nom: 'Philippines',
    iso2: 'PH',
    iso3: 'PHL',
    phone_code: '+63',
  },
  {
    nombre: 'Gibraltar',
    name: 'Gibraltar',
    nom: 'Gibraltar',
    iso2: 'GI',
    iso3: 'GIB',
    phone_code: '+350',
  },
  {
    nombre: 'Granada',
    name: 'Grenada',
    nom: 'Grenade',
    iso2: 'GD',
    iso3: 'GRD',
    phone_code: '+1 473',
  },
  {
    nombre: 'Guam',
    name: 'Guam',
    nom: 'Guam',
    iso2: 'GU',
    iso3: 'GUM',
    phone_code: '+1 671',
  },
  {
    nombre: 'Guatemala',
    name: 'Guatemala',
    nom: 'Guatemala',
    iso2: 'GT',
    iso3: 'GTM',
    phone_code: '+502',
  },
  {
    nombre: 'Guyana',
    name: 'Guyana',
    nom: 'Guyane',
    iso2: 'GY',
    iso3: 'GUY',
    phone_code: '+592',
  },
  {
    nombre: 'Honduras',
    name: 'Honduras',
    nom: 'Honduras',
    iso2: 'HN',
    iso3: 'HND',
    phone_code: '+504',
  },
  {
    nombre: 'India',
    name: 'India',
    nom: 'Inde',
    iso2: 'IN',
    iso3: 'IND',
    phone_code: '+91',
  },
  {
    nombre: 'Irlanda',
    name: 'Ireland',
    nom: 'Irlande',
    iso2: 'IE',
    iso3: 'IRL',
    phone_code: '+353',
  },
  {
    nombre: 'Islas Caimán',
    name: 'Cayman Islands',
    nom: 'Iles Caïmans',
    iso2: 'KY',
    iso3: 'CYM',
    phone_code: '+1 345',
  },
  {
    nombre: 'Islas Malvinas',
    name: 'Falkland Islands (Malvinas)',
    nom: 'Iles Falkland (Malvinas',
    iso2: 'FK',
    iso3: 'FLK',
    phone_code: '+500',
  },
  {
    nombre: 'Islas Vírgenes Británicas',
    name: 'Virgin Islands',
    nom: 'Iles Vierges',
    iso2: 'VG',
    iso3: 'VGB',
    phone_code: '+1 284',
  },
  {
    nombre: 'Islas Vírgenes de los Estados Unidos',
    name: 'United States Virgin Islands',
    nom: 'Îles Vierges américaines',
    iso2: 'VI',
    iso3: 'VIR',
    phone_code: '+1 340',
  },
  {
    nombre: 'Jamaica',
    name: 'Jamaica',
    nom: 'Jamaïque',
    iso2: 'JM',
    iso3: 'JAM',
    phone_code: '+1 876',
  },
  {
    nombre: 'México',
    name: 'Mexico',
    nom: 'Mexique',
    iso2: 'MX',
    iso3: 'MEX',
    phone_code: '+52',
  },
  {
    nombre: 'Nicaragua',
    name: 'Nicaragua',
    nom: 'Nicaragua',
    iso2: 'NI',
    iso3: 'NIC',
    phone_code: '+505',
  },
  {
    nombre: 'Nueva Zelanda',
    name: 'New Zealand',
    nom: 'Nouvelle-Zélande',
    iso2: 'NZ',
    iso3: 'NZL',
    phone_code: '+64',
  },
  {
    nombre: 'Panamá',
    name: 'Panama',
    nom: 'Panama',
    iso2: 'PA',
    iso3: 'PAN',
    phone_code: '+507',
  },
  {
    nombre: 'Paraguay',
    name: 'Paraguay',
    nom: 'Paraguay',
    iso2: 'PY',
    iso3: 'PRY',
    phone_code: '+595',
  },
  {
    nombre: 'Perú',
    name: 'Peru',
    nom: 'Pérou',
    iso2: 'PE',
    iso3: 'PER',
    phone_code: '+51',
  },
  {
    nombre: 'Puerto Rico',
    name: 'Puerto Rico',
    nom: 'Porto Rico',
    iso2: 'PR',
    iso3: 'PRI',
    phone_code: '+1',
  },
  {
    nombre: 'Reino Unido',
    name: 'United Kingdom',
    nom: 'Royaume-Uni',
    iso2: 'GB',
    iso3: 'GBR',
    phone_code: '+44',
  },
  {
    nombre: 'República Dominicana',
    name: 'Dominican Republic',
    nom: 'République Dominicaine',
    iso2: 'DO',
    iso3: 'DOM',
    phone_code: '+1 809',
  },
  {
    nombre: 'Santa Lucía',
    name: 'Saint Lucia',
    nom: 'Sainte-Lucie',
    iso2: 'LC',
    iso3: 'LCA',
    phone_code: '+1 758',
  },
  {
    nombre: 'Sudáfrica',
    name: 'South Africa',
    nom: 'Afrique du Sud',
    iso2: 'ZA',
    iso3: 'ZAF',
    phone_code: '+27',
  },
  {
    nombre: 'Trinidad y Tobago',
    name: 'Trinidad and Tobago',
    nom: 'Trinidad et Tobago',
    iso2: 'TT',
    iso3: 'TTO',
    phone_code: '+1 868',
  },
  {
    nombre: 'Uruguay',
    name: 'Uruguay',
    nom: 'Uruguay',
    iso2: 'UY',
    iso3: 'URY',
    phone_code: '+598',
  },
  {
    nombre: 'Venezuela',
    name: 'Venezuela',
    nom: 'Venezuela',
    iso2: 'VE',
    iso3: 'VEN',
    phone_code: '+58',
  },

  // ============================================================================
  // PAÍSES COMENTADOS - No hablan inglés ni español como idioma principal
  // ============================================================================
  // Para restaurar la lista completa, consultar: countryData.full.backup.ts
  // ============================================================================

  // {
  //   nombre: 'Afganistán',
  //   name: 'Afghanistan',
  //   iso2: 'AF',
  //   iso3: 'AFG',
  //   phone_code: '+93',
  // },
  // ... (resto de 180+ países comentados)
];
